version: "3"
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    hostname: ipfs
    volumes:
    - "./export:/export"
    - "./data/ipfs:/data/ipfs"
    ports:
      - 80:8081
      - 4001:4001
      - 5001:5001
      - 8080:8082
   
